fix(dialog): fix dialog position or overflow menu
IBM/carbon-components-angular pull request #1558
Opened 2020-10-05 16:11 UTC by DusanMilko

Fixed https://github.com/IBM/carbon-components-angular/issues/1557

2020-10-05 17:10 UTC, theiliad requested changes

2020-10-05 17:10 UTC, theiliad commented on src/dialog/overflow-menu/overflow-menu-pane.component.ts
> +		}
how about `return val.includes(styles[attr])`?

2020-10-05 18:23 UTC, DusanMilko commented on src/dialog/overflow-menu/overflow-menu-pane.component.ts
> +		}
Updated, great feedback!

2020-10-13 19:32 UTC, cal-smith approved these changes
Nice! We'll have to integrate this into the upstream position utility at some point, but for now this looks great! 🎉

2020-10-13 20:20 UTC, DusanMilko commented
> Nice! We'll have to integrate this into the upstream position utility at some point, but for now this looks great! 🎉

Yeah, agreed. I'll also apply this to other components that have a similar issue like dropdown and etc.

2020-10-13 20:36 UTC, cal-smith commented
Sounds good

2020-10-13 20:37 UTC, merged