fix: adds size control for skeleton placeholder
IBM/carbon-components-angular pull request #1608
Opened 2020-11-10 18:05 UTC by jdoyle65

Addresses #1607 

The current `bx--skeleton__placeholder` class has a fixed `6.5rem` width and height. This PR changes `ibm-skeleton-placholder` to render as a block element, and sets the `bx--skeleton__placeholder` element inside of it to fill the width/height of its container.

Using these changes, we can freely manipulate the size of the skeleton placeholder to fit any need.

#### Changelog

**Changed**

* `skeleton-placeholder.component.ts`
* `skeleton.stories.ts`

#### Screenshot

![image](https://user-images.githubusercontent.com/2348003/98711596-8d9ffa80-235b-11eb-921a-50a2a5a94e35.png)

2020-11-10 18:25 UTC, cal-smith requested changes
This is by design: https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/skeleton/_skeleton-placeholder.scss

If we can get some consensus on the `carbon-components` side on how the skeleton should behave and be sized, we can make the updates here as needed. As is this would be a breaking change, since users are expecting a fixed width/height skeleton.

If there's a way to introduce this functionality in a non-breaking way, that preserves Carbon compatibility by default, we can go with that!

Overall I think skeleton _should_ work like this, I just want to make sure we're approaching it the right way.

2020-11-10 18:49 UTC, jdoyle65 commented
@cal-smith it appears that the React library approaches this by allowing the developer to apply their own classes against the placeholder: https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/SkeletonPlaceholder/SkeletonPlaceholder.js

I'm trying to identify the use-case of the fixed-size placeholder in the link provided. Any insight?

2020-11-12 16:38 UTC, cal-smith commented
> @cal-smith it appears that the React library approaches this by allowing the developer to apply their own classes against the placeholder: https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/SkeletonPlaceholder/SkeletonPlaceholder.js

Ah interesting! It may be best if we take that approach ... That keeps our default behaviour for now, and allows users to override as needed

> I'm trying to identify the use-case of the fixed-size placeholder in the link provided. Any insight?

I'm not sure 😀 It's definitely a bit of a odd design decision.

2020-11-12 17:54 UTC, theiliad approved these changes

2021-06-04 18:19 UTC, cal-smith commented
Hey @jdoyle65 👋 this has been stagnant for a while, still totally down to take a generic placeholder component if you have time to work on this some more ... Otherwise we can close this out for now and pick it back up later 👍

2021-06-08 19:13 UTC, cal-smith commented
It's been a few days, so I'm going to close this one out. More than happy to take this contribution in the future!

2021-06-08 19:13 UTC, closed without merging