feat(form controls): add warning state
IBM/carbon-components-angular pull request #1767
Opened 2021-03-22 19:43 UTC by cal-smith

Closes IBM/carbon-components-angular#1750

Adds `warn` and `warnText` to all the form components mentioned in #1750.

2021-03-22 19:53 UTC, zvonimirfras requested changes
I'd probably expect inputs be called `warning` and `warningText`.
Looks good otherwise.

2021-03-22 19:53 UTC, zvonimirfras commented on src/combobox/combobox.component.ts
> + 	* Set to `true` to show a warning (contents set by warningText)
```suggestion
 	* Set to `true` to show a warning (contents set by warnText)
```

2021-03-22 19:53 UTC, zvonimirfras commented on src/datepicker-input/datepicker-input.component.ts
> +	  * Set to `true` to show a warning (contents set by warningText)
```suggestion
	  * Set to `true` to show a warning (contents set by warnText)
```

2021-03-22 20:19 UTC, cal-smith commented
> I'd probably expect inputs be called `warning` and `warningText`.
> Looks good otherwise.

Yeah, I had it that way initially, but then I noticed that react was using `warn` instead ... I'm flexible either way, `warn` is shorter and most similar to `invalid` so that's a plus ...

2021-03-23 12:59 UTC, zvonimirfras approved these changes

2021-03-24 05:39 UTC, Donisius approved these changes

2021-03-24 05:39 UTC, merged