feat(datepicker): Add keyboard navigation
IBM/carbon-components-angular pull request #1772
Opened 2021-03-30 19:05 UTC by Donisius

Closes #1740

2021-03-31 13:24 UTC, zvonimirfras requested changes

2021-03-31 13:24 UTC, zvonimirfras commented on src/datepicker/datepicker.component.ts
> +		if (this.isFlatpickrLoaded()) {
How about a guard?

2021-03-31 13:24 UTC, zvonimirfras commented on src/datepicker/datepicker.component.ts
> +						(
this looks... 🤔 
If `this.flatpickrInstance.calendarContainer` is falsey, `focus` will throw?
So how about we assign the value to a var, check if it's falsey and focus in the if body?
That should also make this more readable.

2021-04-07 14:16 UTC, zvonimirfras approved these changes

2021-04-08 15:44 UTC, cal-smith approved these changes
Neato ✨

2021-04-10 01:43 UTC, merged