fix(select): fix reactive form functionality and allow selected to be initialized through value and options tags
IBM/carbon-components-angular pull request #1778
Opened 2021-04-02 17:54 UTC by Donisius

Closes #1776

We cannot use the `value` property on select since default selected values through options tags would be ignored if a `value` is not set by the caller. #1754 addresses this but using an `attribute` means that the `attribute value` cannot change after initialization, which makes setting values through reactive forms not possible.

2021-04-07 18:13 UTC, zvonimirfras requested changes

2021-04-19 14:55 UTC, cal-smith approved these changes
LGTM!

2021-05-23 10:42 UTC, maksym-plotnikov commented
Can You check CI errors?

2021-05-25 19:50 UTC, cal-smith commented
> Can You check CI errors?

Looks like the GitHub backend borked. Just resent the CodeQL jobs.

2021-05-27 22:47 UTC, merged