fix(label) add 'for' as an input for ibm-label
IBM/carbon-components-angular pull request #1785
Opened 2021-04-06 19:22 UTC by ozatici

ibm-label doesn't support the use of "for" as an input, which is an accessibility violation - add it as an input rather than auto-generating it.

2021-04-07 18:43 UTC, zvonimirfras requested changes
Thanks for the effort, Sarah!
`ibm-label` doesn't need to support `for` attribute, `label` needs to have one, and it does have an auto-generated one. Yes, it would be better if it was customizable with a sensible default.
Instead of adding a `for` input to `ibm-label`, which would make DOM have more than one element with the same `for`, how about we make `labelInputId` an input?

```
	@Input labelInputID = "ibm-label-" + Label.labelCounter;
```

Is there a scenario which can't be solved with that?

2021-04-07 18:51 UTC, ozatici commented
How is it possible to make the label match the id of the input it corresponds to if it is auto generated? I need to be able to modify the for of label so that it matches the id of the input box it describes, to match accessibility standards. 

The point of PR wasn't to give a labelInputId to ibm-label, it was to be able to control what the 'for' of label is so that i can modify it to match the input it describes. 


This is what the accessibility flag is identifying as a violation - we have a lot of these coming up. If there is a workaround to fix this violation, I'm open to that as well

<img width="797" alt="Screen Shot 2021-04-07 at 14 49 47" src="https://user-images.githubusercontent.com/18648691/113918681-b87a6780-97b0-11eb-8fb3-c6407071ad15.png">

2021-04-07 19:36 UTC, zvonimirfras commented
> How is it possible to make the label's for match the id of the input it corresponds to if it is auto-generated? I need to be able to modify the for of the label so that it matches the id of the input box it describes, to meet accessibility standards.
> 
> The point of PR wasn't to give a labelInputId to ibm-label that is modifiable, it was to be able to control what the 'for' of label is so that I can modify it to match the id of the input it describes.
> 
> This is what the accessibility flag is identifying as a violation - we have a lot of these coming up. If there is a workaround to fix this violation, I'm open to that as well.
> 

Well, if `labelInputId` is an `@Input`, developer could provide the value for it, which is then passed down to label's `for` attribute.

By assigning a default value, as in my previous comment, if developer doesn't provide the value, the component would pass the generated id to the label's `for` attribute.

Note that if any of the supported input elements (`input,textarea,div`) are children of `ibm-label`, then developers don't even need to assign anything manually (since the generated id will be used) and won't get an accessibility violation.

2021-04-07 19:50 UTC, ozatici commented
> Note that if any of the supported input elements (`input,textarea,div`) are children of `ibm-label`, then developers don't even need to assign anything manually (since the generated id will be used) and won't get an accessibility violation.


You mean as it is now? Or if I add the labelInputId input? Right now i have input elements that are children of ibm-label and am getting accessibility violations..

2021-04-07 19:58 UTC, zvonimirfras commented
> > Note that if any of the supported input elements (`input,textarea,div`) are children of `ibm-label`, then developers don't even need to assign anything manually (since the generated id will be used) and won't get an accessibility violation.
> 
> You mean as it is now? Or if I add the labelInputId input? Right now i have input elements that are children of ibm-label and am getting accessibility violations..

From what I can see [in the demo](https://angular.carbondesignsystem.com/?path=/story/components-input--label), generated `for` attribute on the `label` element and `id` on the `input` element are correctly set, and there shouldn't be any violations around that.
If `labelInputId` was an input, it would allow developers to customize it and even use it with `input` elements placed elsewhere.

2021-04-07 20:03 UTC, ozatici commented
when i assign an id to the input, it doesn't match the randomly generated for on the label. this is my code:

```
<ibm-label [invalidText]="'Country required'"  id="overview_genInfo_countryLabel"> Country
            <input ibmText [value]="countryDesc" [disabled] = "true" [theme] = "'light'" id="overview_genInfo_countryInput" aria-labelledby="overview_genInfo_countryLabel" [epDisabler]="isQuoteUpdatable">
          </ibm-label>
```

I am getting this:

The value "ibm-label-70" of the 'for' attribute is not the 'id' of a valid <input> element

2021-04-07 20:12 UTC, zvonimirfras commented
> when i assign an id to the input, it doesn't match the randomly generated for on the label. this is my code:
> 
> ```
> <ibm-label [invalidText]="'Country required'"  id="overview_genInfo_countryLabel"> Country
>             <input ibmText [value]="countryDesc" [disabled] = "true" [theme] = "'light'" id="overview_genInfo_countryInput" aria-labelledby="overview_genInfo_countryLabel" [epDisabler]="isQuoteUpdatable">
>           </ibm-label>
> ```
> 
> I am getting this:
> 
> The value "ibm-label-70" of the 'for' attribute is not the 'id' of a valid element

Which is a good reason for giving developers control over `labelInputId`. Which this PR does now.
When this PR is merged, you won't have to explicitly assign that id to `input`, it should be enough to just give `labelInputId` to `ibm-label` and it should do the right thing.

2021-04-07 20:13 UTC, ozatici commented
> > when i assign an id to the input, it doesn't match the randomly generated for on the label. this is my code:
> > ```
> > <ibm-label [invalidText]="'Country required'"  id="overview_genInfo_countryLabel"> Country
> >             <input ibmText [value]="countryDesc" [disabled] = "true" [theme] = "'light'" id="overview_genInfo_countryInput" aria-labelledby="overview_genInfo_countryLabel" [epDisabler]="isQuoteUpdatable">
> >           </ibm-label>
> > ```
> > 
> > 
> > I am getting this:
> > The value "ibm-label-70" of the 'for' attribute is not the 'id' of a valid element
> 
> Which is a good reason for giving developers control over `labelInputId`. Which this PR does now.
> When this PR is merged, you won't have to explicitly assign that id to `input`, it should be enough to just give `labelInputId` to `ibm-label` and it should do the right thing.

Okay great, makes sense, thanks for being willing to comment back and forth, appreciate the feedback!!!

2021-04-07 20:13 UTC, zvonimirfras approved these changes

2021-04-08 15:37 UTC, cal-smith approved these changes
LGTM! Thanks for contributing this 🚀

2021-04-08 15:37 UTC, merged