feat(context-menu): add a simple context menu component
IBM/carbon-components-angular pull request #1812
Opened 2021-05-10 19:30 UTC by cal-smith

Adds a simple context-menu implementation. [See here](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-contextmenu--context-menu) for the existing react implementation this is based on. We deviate in a few ways, and add some component level styles to make things behave, but all the functionality should be the same.

This doesn't handle displaying on right click - We can add a service later to deal with that (I'm thinking something that could serve as a proper foundation for the dialog service ... Maybe we can address some of the positioning bugs at the same time).

2021-05-10 20:17 UTC, zvonimirfras requested changes

2021-05-10 20:17 UTC, zvonimirfras commented on src/context-menu/context-menu-item.component.ts
> +	Input, Output,
```suggestion
	Input,
	Output,
```
?

2021-05-10 20:17 UTC, zvonimirfras commented on src/context-menu/context-menu-item.component.ts
> +
```suggestion
```

or keeping for later?

2021-05-10 20:17 UTC, zvonimirfras commented on src/context-menu/context-menu.component.ts
> +		}
```suggestion
		if (changes.open && changes.open.currentValue) {
			this.focusMenu();
		}
```

2021-05-10 20:17 UTC, zvonimirfras commented on src/context-menu/context-menu.component.ts
> +				});
```suggestion
				return subMenu.menuItems.some(subMenuItem => menuItem === subMenuItem);
```

2021-05-10 20:17 UTC, zvonimirfras commented on src/context-menu/context-menu.component.ts
> +		if (event.key === "ArrowDown") {
Looks like you're trying to create a switch-case type flow with ifs on event.key. Maybe just use switch?

2021-05-10 21:09 UTC, cal-smith commented on src/context-menu/context-menu-item.component.ts
> +
Nope! Missed that one!

2021-05-13 13:46 UTC, zvonimirfras submitted a review, later dismissed
Just this line and we're good to go.

2021-05-13 13:46 UTC, zvonimirfras commented on src/context-menu/context-menu.component.ts
> +
```suggestion
```

2021-05-13 15:01 UTC, merged