fix defect 2022
IBM/carbon-components-angular pull request #2003
Opened 2022-02-14 07:23 UTC by GSSCDylan

Put role="menuitem" into <li> element instead of <a> element

Closes IBM/carbon-components-angular#

{{short description}}

#### Changelog

**New**

* {{new thing}}

**Changed**

* {{change thing}}

**Removed**

* {{removed thing}}

2022-03-15 14:20 UTC, GSSCDylan commented
> 

I mean defect 2002, https://github.com/IBM/carbon-components-angular/issues/2002
Sorry for the typo!

2022-03-21 15:10 UTC, zvonimirfras requested changes
Thanks for doing this, Dylan. Just one quick thing 🙂

2022-03-21 15:10 UTC, zvonimirfras commented on src/ui-shell/header/header-item.component.ts
> +			role="menuitem">
```suggestion
		<li
			style="height: 100%"
			role="menuitem">
```

2022-03-28 14:33 UTC, zvonimirfras approved these changes

2022-03-28 14:33 UTC, merged