Fix #1989
IBM/carbon-components-angular pull request #2031
Opened 2022-02-21 05:12 UTC by GSSCDylan

Closes IBM/carbon-components-angular#

{{short description}}

#### Changelog

**Changed**
tabs
* {{change thing}}
Add title attribute for button of tab-headers, so Jaws can tell the user what's the button used for

2022-03-11 10:55 UTC, GSSCDylan commented on src/tabs/tab-headers.component.ts
> +				title="previous"
Fix it as your suggestion, thank you! Please help to review it again!

2022-03-23 17:02 UTC, Donisius requested changes
Thanks for doing this! Just have a couple of small changes!

2022-03-23 17:02 UTC, Donisius commented on src/ui-shell/header/header-item.component.ts
> +			role="menuitem">
```suggestion
		<li
			style="height: 100%"
			role="menuitem">
```

2022-03-30 19:45 UTC, Donisius approved these changes

2022-04-05 13:15 UTC, zvonimirfras commented
@GSSCDylan good to go once build issues are resolved 👍

2022-04-06 03:09 UTC, GSSCDylan commented
> @GSSCDylan good to go once build issues are resolved 👍

Thanks, I'm not familiar with build process, is there anything need I to take action?

2022-04-07 13:06 UTC, zvonimirfras commented
> > @GSSCDylan good to go once build issues are resolved 👍
> 
> Thanks, I'm not familiar with build process, is there anything need I to take action?

Luckily, you don't need to be familiar with the process to read the [build log](https://app.travis-ci.com/github/IBM/carbon-components-angular/builds/248901929) 😉 

From there, it says `NullInjectorError: No provider for I18n` which sounds like there's no provider of `I18n`.
Looking at your PR, you _did_ introduce the `I18n` to tabs, and tabs module (`src/tabs/tabs.module.ts`) doesn't seem to already have the provider in.

This looks like a standard Angular workflow so it would be a good first step to look at.

You can generate the build log locally by running `npm run build`. It will give you insights what might be going wrong in case the build fails.

2022-04-08 12:00 UTC, GSSCDylan commented
> > > @GSSCDylan good to go once build issues are resolved 👍
> > 
> > 
> > Thanks, I'm not familiar with build process, is there anything need I to take action?
> 
> Luckily, you don't need to be familiar with the process to read the [build log](https://app.travis-ci.com/github/IBM/carbon-components-angular/builds/248901929) 😉
> 
> From there, it says `NullInjectorError: No provider for I18n` which sounds like there's no provider of `I18n`. Looking at your PR, you _did_ introduce the `I18n` to tabs, and tabs module (`src/tabs/tabs.module.ts`) doesn't seem to already have the provider in.
> 
> This looks like a standard Angular workflow so it would be a good first step to look at.
> 
> You can generate the build log locally by running `npm run build`. It will give you insights what might be going wrong in case the build fails.

fix the issue by import I18nModule into tabs.component.spec and tab.headers.component.spec

2022-04-08 12:03 UTC, GSSCDylan commented
> > > @GSSCDylan good to go once build issues are resolved 👍
> > 
> > 
> > Thanks, I'm not familiar with build process, is there anything need I to take action?
> 
> Luckily, you don't need to be familiar with the process to read the [build log](https://app.travis-ci.com/github/IBM/carbon-components-angular/builds/248901929) 😉
> 
> From there, it says `NullInjectorError: No provider for I18n` which sounds like there's no provider of `I18n`. Looking at your PR, you _did_ introduce the `I18n` to tabs, and tabs module (`src/tabs/tabs.module.ts`) doesn't seem to already have the provider in.
> 
> This looks like a standard Angular workflow so it would be a good first step to look at.
> 
> You can generate the build log locally by running `npm run build`. It will give you insights what might be going wrong in case the build fails.

fix the issue by import I18nModule into tabs.component.spec and tab.headers.component.spec

2022-04-08 17:11 UTC, zvonimirfras approved these changes

2022-04-08 17:22 UTC, merged