feat: index carbon  angular
IBM/carbon-components-angular pull request #2081
Opened 2022-04-28 02:17 UTC by andreancardona

https://github.com/carbon-design-system/carbon-platform/issues/514

## Description:

- This PR indexes `carbon-components-angular`

## Note:

We still need the following thumbnails:

2022-04-28 15:34 UTC, francinelucca commented on src/carbon.yml
> +  externalDocsUrl: https://angular.carbondesignsystem.com/?path=/story/components-welcome--to-carbon-angular
```suggestion
  externalDocsUrl: https://angular.carbondesignsystem.com
```

2022-04-28 15:34 UTC, francinelucca commented on src/carbon.yml
> +        url: https://angular.carbondesignsystem.com/?path=/story/components-link
incorrect externalDocsUrl

2022-04-28 15:34 UTC, francinelucca commented on src/carbon.yml
> +        url: https://angular.carbondesignsystem.com/?path=/story/components-link
icorrect externalDocsUrl, incorrect demoLink url

2022-04-28 15:34 UTC, francinelucca commented on src/carbon.yml
> +          url: https://angular.carbondesignsystem.com/?path=/story/components-number
incorrect ExternalDocsUrl

2022-04-28 15:46 UTC, andreancardona commented on src/carbon.yml
> +    externalDocsUrl: https://www.carbondesignsystem.com/components/inline-loading/usage
```suggestion
    externalDocsUrl: https://carbondesignsystem.com/components/link/usage
```

2022-04-28 15:49 UTC, francinelucca commented on src/carbon.yml
> +    name: icon
```suggestion
    name: Icon
```

2022-04-28 15:52 UTC, andreancardona commented on src/carbon.yml
> +    externalDocsUrl: https://www.carbondesignsystem.com/components/inline-loading/usage
```suggestion
    externalDocsUrl: https://carbondesignsystem.com/components/link/usage

2022-04-28 15:54 UTC, andreancardona commented on src/carbon.yml
> +    externalDocsUrl: https://www.carbondesignsystem.com/components/inline-loading/usage
```suggestion
    externalDocsUrl: https://carbondesignsystem.com/components/loading/usage/
```

2022-04-28 15:56 UTC, andreancardona commented on src/carbon.yml
> +        url: https://angular.carbondesignsystem.com/?path=/story/components-link
```suggestion
        url: https://angular.carbondesignsystem.com/?path=/story/components-loading
```

2022-05-03 15:31 UTC, francinelucca reviewed
LGTM! 🎉

2022-05-03 16:28 UTC, aubrey-oneal commented on src/carbon.yml
> +      - contextual-navigation
Delete contextual-navigation tag. Add media and content-element tags.

2022-05-03 16:28 UTC, aubrey-oneal commented on src/carbon.yml
> +      - input-control
Approved 👍

2022-05-03 16:32 UTC, aubrey-oneal commented on src/carbon.yml
> +      - data-display
Approved 👍

2022-05-03 16:35 UTC, aubrey-oneal commented on src/carbon.yml
> +      - contextual-navigation
Delete contextual-navigation. Add input-control.

2022-05-03 16:37 UTC, aubrey-oneal commented on src/carbon.yml
> +      - data-display
Approved 👍

2022-05-03 16:38 UTC, aubrey-oneal commented on src/carbon.yml
> +      - data-display
Delete data-display. Add input-control.

2022-05-03 16:40 UTC, aubrey-oneal commented on src/carbon.yml
> +      - data-display
Approved 👍

2022-05-03 16:45 UTC, aubrey-oneal commented on src/carbon.yml
> +      - data-display
Delete data-display. Add system-feedback.

2022-05-03 16:45 UTC, aubrey-oneal requested changes
I approved several tagged components but suggested a few changes.

2022-05-03 18:05 UTC, andreancardona commented on src/carbon.yml
> +      - contextual-navigation
```suggestion
      - input-control
```

2022-05-03 18:06 UTC, andreancardona commented on src/carbon.yml
> +      - contextual-navigation
```suggestion
      - media
      - content-element
```

2022-05-03 18:06 UTC, andreancardona commented on src/carbon.yml
> +      - data-display
```suggestion
      - data-display
      - content-element
```

2022-05-03 18:07 UTC, andreancardona commented on src/carbon.yml
> +      - data-display
```suggestion
      - input-control
```

2022-05-03 18:10 UTC, andreancardona commented on src/carbon.yml
> +      - data-display
```suggestion
      - data-display
      - content-element
```

2022-05-03 18:11 UTC, andreancardona commented on src/carbon.yml
> +      - content-element
```suggestion
```

2022-05-03 18:12 UTC, andreancardona commented on src/carbon.yml
> +      - content-element
```suggestion
      - content-element
```

2022-05-03 18:12 UTC, andreancardona commented on src/carbon.yml
> +      - content-element
```suggestion
```

2022-05-04 19:18 UTC, merged