fix(table): enable horizontal scroll in table
IBM/carbon-components-angular pull request #2128
Opened 2022-06-02 17:01 UTC by yinglejia

Closes IBM/carbon-components-angular#

Enable horizontal scroll in table to match Carbon React implementation. Refer Carbon React implementation: https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/DataTable/Table.js#L34

<img width="411" alt="image" src="https://user-images.githubusercontent.com/34791554/171684441-6067ba09-29b4-44c9-af22-38792a8f0776.png">

<img width="973" alt="image" src="https://user-images.githubusercontent.com/34791554/171684509-419df070-2079-4677-9bb7-c3be5f2e0ec2.png">

#### Changelog

**New**

* {{new thing}}

**Changed**

* {{change thing}}

**Removed**

* {{removed thing}}

2022-06-28 23:12 UTC, Akshat55 commented
Holding on merging - as we discuss with @carbon/styles team to add display block to `.bx--data-table-content` class. We can then use @hostbind the class - This would prevent unnecessary elements in template & make it easier to manage.

For the time being, you can add `.bx--data-table-content` class to ibm-table tag with display set to block as follows:

```html
<ibm-table class="bx--data-table-content" style="display: block">
     ....
</ibm-table>
```

2022-06-29 00:46 UTC, yinglejia commented
> Holding on merging - as we discuss with @carbon/styles team to add display block to `.bx--data-table-content` class. We can then use @hostbind the class - This would prevent unnecessary elements in template & make it easier to manage.
> 
> For the time being, you can add `.bx--data-table-content` class to ibm-table tag with display set to block as follows:
> 
> ```
> <ibm-table class="bx--data-table-content" style="display: block">
>      ....
> </ibm-table>
> ```

Thanks for the update, @Akshat55. Actually my initial attempt was to use @hostbind the class. I did not end up using that approach since the table component also @hostbind `bx--data-table_inner-container` for sticky header. So we would end up having both `.bx--data-table-content` and `bx--data-table_inner-container` on the host. I don't know Carbon team intends to support this or not. Adding display: block is the easy part.

2022-09-02 19:55 UTC, Akshat55 requested changes
Hi @yinglejia, Thanks for your contribution & sorry for the long delay!

We have decided to go with leaving the styles in components file in carbon v10 (CCA v4), but for v11 they will be added in @carbon/styles package.

That being said, I have also merged master into the branch so just a friendly reminder,  please git pull.

2022-09-02 19:55 UTC, Akshat55 commented on src/table/table.component.ts
> +	<div class="bx--data-table-content">
```suggestion
```

Let's apply the style directly to host & add styles.

2022-09-02 19:55 UTC, Akshat55 commented on src/table/table.component.ts
> +	</div>
```suggestion
```

2022-09-02 19:55 UTC, Akshat55 commented on src/table/table.component.ts
>  	`
```suggestion
	`,
	styles: [`
		:host {
			display: block;
		}
	`]
```

2022-09-02 19:55 UTC, Akshat55 commented on src/table/table.component.ts
>  export class Table implements AfterViewInit, OnDestroy {
Where best fits in class, add @HostBinding as seen below. Run npm run lint:fix to ensure the order is corect.

```suggestion
export class Table implements AfterViewInit, OnDestroy {
	@HostBinding("class.bx--data-table-content") tableContent = true;
```

2022-09-06 20:22 UTC, closed without merging

2022-09-06 20:30 UTC, yinglejia commented
New PR created: https://github.com/IBM/carbon-components-angular/pull/2235