Fix theme to be avaliable for all types of code-snippet
IBM/carbon-components-angular pull request #2210
Opened 2022-07-21 18:20 UTC by MoizMasud

Closes IBM/carbon-components-angular https://github.com/IBM/carbon-components-angular/issues/2208

2022-07-29 01:58 UTC, Akshat55 requested changes
Good to merge once DCO passes. 

@MoizMasud can you please follow the[ DCO instructions](https://github.com/IBM/carbon-components-angular/pull/2210/checks?check_run_id=7455510769) to fix this error, thanks.

Let me know on slack if you have trouble with this.

2022-07-29 16:53 UTC, MoizMasud commented
> Good to merge once DCO passes.
> 
> @MoizMasud can you please follow the[ DCO instructions](https://github.com/IBM/carbon-components-angular/pull/2210/checks?check_run_id=7455510769) to fix this error, thanks.
> 
> Let me know on slack if you have trouble with this.

done

2022-08-04 22:32 UTC, Akshat55 approved these changes

2022-08-08 18:48 UTC, zvonimirfras approved these changes

2022-08-08 18:59 UTC, merged