fix: set default aria-label for breadcrumb nav
IBM/carbon-components-angular pull request #2212
Opened 2022-07-26 04:42 UTC by kush-savani

Closes #2185 

Set default aria-label for breadcrumb nav

#### Changelog

**New**

* add new `BREADCRUMB` key in `en.ts` file.
* Set default `aria-lable` for breadcrumb component.

**Before**
<img width="1549" alt="Screenshot 2022-07-14 at 9 34 21 AM" src="https://user-images.githubusercontent.com/49565062/178896045-78f90f79-3d5e-4c57-8cc3-c48f7b431b26.png">

**After**
<img width="1312" alt="Screenshot 2022-07-14 at 9 33 42 AM" src="https://user-images.githubusercontent.com/49565062/178896128-c8cd86b7-6ef5-4aec-b1f7-f65a0becac20.png">

2022-07-29 01:59 UTC, Akshat55 commented
Will wait for credits to be added to travis before merging.

2022-08-09 13:35 UTC, Akshat55 approved these changes

2022-08-09 15:34 UTC, Akshat55 requested changes

2022-08-09 15:34 UTC, Akshat55 commented on src/breadcrumb/breadcrumb.component.ts
>  import { DomSanitizer } from "@angular/platform-browser";
```suggestion
```

Could you remove DomSanitizer import & dependency injection in constructor as well, please. 

It isn't being used anywhere in the code & seems to have remained from previous changes. Thanks!

2022-08-09 15:34 UTC, Akshat55 commented on src/breadcrumb/breadcrumb.component.ts
> +	) { }
```suggestion
	constructor(protected i18n: I18n, @Optional() protected router: Router) { }
```

2022-08-18 18:20 UTC, Akshat55 approved these changes
Code is good to go, just need to fix DCO

2022-08-22 14:25 UTC, Akshat55 approved these changes

2022-08-22 15:03 UTC, zvonimirfras approved these changes

2022-08-22 15:03 UTC, merged